/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandColorPicker: typeof import('./src/@core/components/BrandColorPicker.vue')['default']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    LogoIcon: typeof import('./src/@core/components/LogoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeChanger: typeof import('./src/@core/components/theme-changer/ThemeChanger.vue')['default']
    ThemeDropdown: typeof import('./src/@core/components/theme-changer/ThemeDropdown.vue')['default']
  }
}
